version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
       - "27017:27017"
    volumes:
       - mongodb1:/data/db
    environment:
       - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=1
  brokerimporter:
    build: .
    ports:
      - "8080:8080"
    restart: always
    container_name: brokerimporter
    environment:
       - MONGO_IP=database
    links:
       - "mongo:database"
volumes:
  mongodb1:
    driver: local
